version: "3.9"

services:
  books-app:
    build: .
    container_name: books-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "aerich upgrade && uvicorn app.main:app --host 0.0.0.0 --port 8000"
